### ISSUE TITLE
Provide specific instructions on how to play Gothic I

### ISSUE THREAD

**Issue by jtrees** [degenerated1123/REGoth#10]
Currently the `README` states to specifiy "one of the Zen-Files found in a .vdf-files in the games data/-directory". But it doesn't explain how to find out which Zen files are available. I presume the VDFs are some form of archive but haven't been able to extract them. Some more info on this would be helpful.

Furthermore, I could imagine many people are primarily interested in this project so they can play the game, rather than developing the engine, so simply providing copy-pastable lines for launching Gothic I or Gothic II would be cool.

**Comment by degenerated1123** [comment]
Some of the worlds if Gothic I are called `world.zen`, `oldmine.zen` and `freemine.zen`.

I will add them to the readme later, good idea!

**Comment by degenerated1123** [comment]
I have added example-commandlines for the most important worlds for G1 and G2 to the readme.

**Comment by jtrees** [comment]
Cool, I was able to get it working! Thanks for your help.

I'll admit I was somewhat disappointed (though not surprised) to see the game isn't in a playable state yet, but what you have so far looks good. Perhaps it would be a good idea to mention that the engine isn't feature complete yet in the `README`.

Speaking of which, some form of roadmap to gauge current progress would be great.

**Comment by degenerated1123** [comment]
A Roadmap would be helpful, yes. 

I'm only working on this project for a couple months now, that's why all the technical features have to be implemented first. I'll put a note about that into the readme.
