### ISSUE TITLE
Typo, Reimplentation -> Reimplementation 

### ISSUE THREAD

**Issue by prokopst** [degenerated1123/REGoth#11]
There is a typo in the description and in the README file.
Reimplentation -> Reimplementation.

**Comment by degenerated1123** [comment]
Always good to have those right in the first sentence... Thanks for telling me!

**Comment by prokopst** [comment]
You still have the typo in the repo description :)

**Comment by degenerated1123** [comment]
Dammit! :D

**Comment by degenerated1123** [comment]
Fixed. Very professional!
