### ISSUE TITLE
Win7 , Visual Studio, Not displaying anything except for bounding boxes:

### ISSUE THREAD

**Issue by ArrrHub** [degenerated1123/REGoth#12]
#> C:\Users\dat\Desktop\regoth\REGoth\build2\bin\Release>REGoth.exe -g "F:\Gothic"-w FREEMINE.zen
Running REGoth Engine
Info: Using F:\Gothic as game root
Info: Loading world FREEMINE.zen on startup
Info: Loading VDF-Archives: [

- F:\Gothic/Data/Anims.vdf
- F:\Gothic/Data/Fonts.vdf
- F:\Gothic/Data/Meshes.vdf
- F:\Gothic/Data/Sound.vdf
- F:\Gothic/Data/Sound_patch2.vdf
- F:\Gothic/Data/Speech.vdf
- F:\Gothic/Data/Speech_babe_speech_engl.vdf
- F:\Gothic/Data/Textures.vdf
- F:\Gothic/Data/Textures_apostroph_patch_neu.vdf
- F:\Gothic/Data/Textures_bikini.vdf
- F:\Gothic/Data/Textures_choicebox_32pixel_modialpha.vdf
- F:\Gothic/Data/Textures_patch.vdf
- F:\Gothic/Data/Textures_Startscreen_ohne_Logo.vdf
- F:\Gothic/Data/Worlds.vdf
]
Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Anims.vdf
Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Fonts.vdf
Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Meshes.vdf
Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Sound.vdf
Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Sound_patch2.vdf
Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Speech.vdf
Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Speech_babe_speech_engl.vd
f
Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Textures.vdf
Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Textures_apostroph_patch_n
eu.vdf
Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Textures_bikini.vdf
Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Textures_choicebox_32pixel
_modialpha.vdf
Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Textures_patch.vdf
Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Textures_Startscreen_ohne_
Logo.vdf
Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Worlds.vdf
Info: ZEN: Reading world...
Info: oCWorld reading chunk: MeshAndBsp
Info: ZEN: Reading mesh...
Info: numPolys: 13202
Info: Num nodes: 4259
Info: Found 3952 non lod polys
Info: Reading mesh '' (Version: 9)
Info: Found 2116 vertices
Info: ZEN: Done reading mesh!
Info: oCWorld reading chunk: VobTree
Info: oCWorld reading chunk: WayNet
Info: Loading 0 freepoints
Info: Loading 177 edges
Info: Done loading edges!
Info: Postprocessing worldmesh...
Info: Generating world collision mesh...
Info: Inserting vobs...
Info: Loading Daedalus compiled script file: F:\Gothic/_work/data/Scripts/_compi
led/GOTHIC.DAT
Info: Zen-File found! Size: 3595531
Info: Reading...
Info: Did not find main-function!
Info: Initializing scripts for world: FREEMINE
Info: DEBUG: ### (0) ### -> B_Scale
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: DEBUG: ### (0) ### -> B_Scale
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: DEBUG: ### (0) ### -> B_Scale
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: DEBUG: ### (0) ### -> B_Scale
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: DEBUG: ### (0) ### -> B_Scale
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: DEBUG: ### (0) ### -> B_Scale
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: DEBUG: ### (0) ### -> B_Scale
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: DEBUG: ### (0) ### -> B_Scale
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: DEBUG: ### (0) ### -> B_Scale
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: DEBUG: ### (0) ### -> B_Scale
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: DEBUG: ### (0) ### -> B_Scale
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: DEBUG: ### (0) ### -> B_Scale
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: DEBUG: ### (0) ### -> B_Scale
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: DEBUG: ### (0) ### -> B_Scale
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: DEBUG: ### (0) ### -> B_Scale
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: DEBUG: ### (0) ### -> B_Scale
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: DEBUG: ### (0) ### -> B_Scale
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: DEBUG: ### (0) ### -> B_Scale
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: DEBUG: ### (0) ### -> B_Scale
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: DEBUG: ### (0) ### -> B_Scale
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: DEBUG: ### (0) ### -> B_Scale
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: DEBUG: ### (0) ### -> B_Scale
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: DEBUG: ### (0) ### -> B_Scale
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: DEBUG: ### (0) ### -> B_Scale
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: DEBUG: ### (0) ### -> B_Scale
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: DEBUG: ### (0) ### -> B_Scale
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
C:\Users\dat\Desktop\regoth\REGoth\src\components\AnimHandler.cpp(83):[void __th
iscall Components:nimHandler:layAnimation(const class std::basic_string<char
,struct std::char_traits<char>,class std::allocator<char> > &)] Failed to find a
nimation: S_RUNL
C:\Users\dat\Desktop\regoth\REGoth\src\components\AnimHandler.cpp(83):[void __th
iscall Components:nimHandler:layAnimation(const class std::basic_string<char
,struct std::char_traits<char>,class std::allocator<char> > &)] Failed to find a
nimation: S_RUNL
C:\Users\dat\Desktop\regoth\REGoth\src\components\AnimHandler.cpp(83):[void __th
iscall Components:nimHandler:layAnimation(const class std::basic_string<char
,struct std::char_traits<char>,class std::allocator<char> > &)] Failed to find a
nimation: S_RUNL
C:\Users\dat\Desktop\regoth\REGoth\src\components\AnimHandler.cpp(83):[void __th
iscall Components:nimHandler:layAnimation(const class std::basic_string<char
,struct std::char_traits<char>,class std::allocator<char> > &)] Failed to find a
nimation: S_RUNL
C:\Users\dat\Desktop\regoth\REGoth\src\components\AnimHandler.cpp(83):[void __th
iscall Components:nimHandler:layAnimation(const class std::basic_string<char
,struct std::char_traits<char>,class std::allocator<char> > &)] Failed to find a
nimation: S_RUNL
C:\Users\dat\Desktop\regoth\REGoth\src\components\AnimHandler.cpp(83):[void __th
iscall Components:nimHandler:layAnimation(const class std::basic_string<char
,struct std::char_traits<char>,class std::allocator<char> > &)] Failed to find a
nimation: S_RUNL
C:\Users\dat\Desktop\regoth\REGoth\src\components\AnimHandler.cpp(83):[void __th
iscall Components:nimHandler:layAnimation(const class std::basic_string<char
,struct std::char_traits<char>,class std::allocator<char> > &)] Failed to find a
nimation: S_RUNL
C:\Users\dat\Desktop\regoth\REGoth\src\components\AnimHandler.cpp(83):[void __th
iscall Components:nimHandler:layAnimation(const class std::basic_string<char
,struct std::char_traits<char>,class std::allocator<char> > &)] Failed to find a
nimation: S_RUNL
C:\Users\dat\Desktop\regoth\REGoth\src\components\AnimHandler.cpp(83):[void __th
iscall Components:nimHandler:layAnimation(const class std::basic_string<char
,struct std::char_traits<char>,class std::allocator<char> > &)] Failed to find a
nimation: S_RUNL
C:\Users\dat\Desktop\regoth\REGoth\src\components\AnimHandler.cpp(83):[void __th
iscall Components:nimHandler:layAnimation(const class std::basic_string<char
,struct std::char_traits<char>,class std::allocator<char> > &)] Failed to find a
nimation: S_RUNL
C:\Users\dat\Desktop\regoth\REGoth\src\components\AnimHandler.cpp(83):[void __th
iscall Components:nimHandler:layAnimation(const class std::basic_string<char
,struct std::char_traits<char>,class std::allocator<char> > &)] Failed to find a
nimation: S_RUNL
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: DEBUG: ### (0) ### -> B_InitGuildAttitudes
C:\Users\dat\Desktop\regoth\REGoth\src\logic\ScriptEngine.cpp(80):[int __thiscal
l Logic::ScriptEngine::runFunction(unsigned int)] DaedalusVM: Safety int was pop
ped by scriptcode!
Info: Inserting player of class 'PC_HERO' at startpoint 'zCVobStartpoint:zCVob'
Info: itemInstance: 4128
C:\Users\dat\Desktop\regoth\REGoth\lib\ZenLib\zenload\zCCSLib.cpp(47):[__thiscal
l ZenLoad::zCCSLib::zCCSLib(const class std::basic_string<char,struct std::char_
traits<char>,class std::allocator<char> > &)] File does not exist

**Comment by degenerated1123** [comment]
You may only need to copy the shaders from the content/-folder again, if you just updated your repository. 

Haven't compiled it on Windows for a while though, so I will try to reproduce that later.

**Comment by ArrrHub** [comment]
So I have actually copied to content folder. Also I have noticed that the day/night cycle is working properly - the colors go slowly from red-ish to blue.

**Comment by degenerated1123** [comment]
I can't even compile it under windows, since the Win32-headers mess my dialog-system up with their #defines. How did you get it to compile?

**Comment by degenerated1123** [comment]
Okay, I resolved all the issues I could find with the windows build. It really shouldn't have compiled for you, so I don't know *what* you actually compiled.

Furthermore, I added a .bat file, which will update the complete git repository for you: `update_git.bat`. Just run that and it will pull everything, including submodules.

**Comment by ArrrHub** [comment]
It didn't compile - I had to fix it :)

**Comment by degenerated1123** [comment]
Aaand now I'm getting the same output as you got before. Just give me a couple more minutes...

**Comment by degenerated1123** [comment]
Allright, I was actually missing some files in the `content/`-directory. The files really should be copied on launch or otherwise found so that you don't have to copy them manually.

**Comment by ArrrHub** [comment]
Great, this issue seems to have been resolved :) More to come.
