### ISSUE TITLE
Wrong paths for Windows + Valuetype name does not match expcted type

### ISSUE THREAD

**Issue by ArrrHub** [degenerated1123/REGoth#13]
So when we are running stuff on Windows, you need to change the paths.

1) Change the case senstive call to detect if there's Windows involved, f.i
 `#if defined(_WIN64) || defined(_WIN32) 
    return string`
2) Change directory "level" symbols from / to \

3) Unfortunately I can't fix that one : 
When loading any .ZEN file I'm getting the following error message : 

> Valuetype name does not match expcted type

It happens at : parserImplBinsafe.cpp : 302
Logs:

> Running REGoth Engine
> Info: No game-root specified! Using the current working-directory as game root.
> Use the '-g' flag to specify this!
> Info: Using F:\Gothic as game root
> Info: No startup-world specified. Using 'addonworld.zen' as default. Use the '-w
> ' flag to specify a ZEN-file!
> Info: Loading world OLDMINE.ZEN on startup
> Info: Loading VDF-Archives: [
- F:\Gothic/Data/Anims.vdf
- F:\Gothic/Data/Fonts.vdf
- F:\Gothic/Data/Meshes.vdf
- F:\Gothic/Data/Sound.vdf
- F:\Gothic/Data/Sound_patch2.vdf
- F:\Gothic/Data/Speech.vdf
- F:\Gothic/Data/Speech_babe_speech_engl.vdf
- F:\Gothic/Data/Textures.vdf
- F:\Gothic/Data/Textures_apostroph_patch_neu.vdf
- F:\Gothic/Data/Textures_bikini.vdf
- F:\Gothic/Data/Textures_choicebox_32pixel_modialpha.vdf
- F:\Gothic/Data/Textures_patch.vdf
- F:\Gothic/Data/Textures_Startscreen_ohne_Logo.vdf
- F:\Gothic/Data/Worlds.vdf
  ]
  Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Anims.vdf
  Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Fonts.vdf
  Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Meshes.vdf
  Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Sound.vdf
  Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Sound_patch2.vdf
  Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Speech.vdf
  Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Speech_babe_speech_engl.vd
  f
  Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Textures.vdf
  Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Textures_apostroph_patch_n
  eu.vdf
  Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Textures_bikini.vdf
  Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Textures_choicebox_32pixel
  _modialpha.vdf
  Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Textures_patch.vdf
  Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Textures_Startscreen_ohne_
  Logo.vdf
  Info: Successfully loaded VDF-Archive: F:\Gothic/Data/Worlds.vdf
  Info: ZEN: Reading world...
  Info: oCWorld reading chunk: MeshAndBsp
  Info: ZEN: Reading mesh...
  Info: numPolys: 31522
  Info: Num nodes: 10805
  Info: Found 9554 non lod polys
  Info: Reading mesh '' (Version: 9)
  Info: Found 4628 vertices
  Info: ZEN: Done reading mesh!
  Info: oCWorld reading chunk: VobTree
  Info: oCWorld reading chunk: WayNet
  Info: Loading 0 freepoints
  Info: Loading 312 edges
  Info: Done loading edges!
  Info: Postprocessing worldmesh...
  Info: Generating world collision mesh...
  Info: Inserting vobs...
  Info: Loading Daedalus compiled script file: F:\Gothic_work\data\Scripts_compi
  led\GOTHIC.DAT
  Info: Zen-File found! Size: 3595531
  Info: Reading...
  Info: Initializing scripts for world: OLDMINE
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3936
  Info: itemInstance: 4337
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3924
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3837
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3837
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3837
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3849
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3849
  Info: itemInstance: 3837
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3849
  Info: itemInstance: 3837
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3843
  Info: itemInstance: 4290
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> Npc_SetPermAttitude()
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3849
  Info: itemInstance: 3837
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3837
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3849
  Info: itemInstance: 3837
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3849
  Info: itemInstance: 3837
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3849
  Info: itemInstance: 3837
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3837
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3837
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3837
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3849
  Info: itemInstance: 3837
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3837
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 4052
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3837
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3837
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3837
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3837
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3915
  Info: itemInstance: 3841
  Info: itemInstance: 3861
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3915
  Info: itemInstance: 3841
  Info: itemInstance: 3861
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3915
  Info: itemInstance: 3841
  Info: itemInstance: 3861
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3915
  Info: itemInstance: 3841
  Info: itemInstance: 3861
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3915
  Info: itemInstance: 3841
  Info: itemInstance: 3861
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3915
  Info: itemInstance: 3841
  Info: itemInstance: 3861
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3915
  Info: itemInstance: 3841
  Info: itemInstance: 3861
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3915
  Info: itemInstance: 3841
  Info: itemInstance: 3861
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3915
  Info: itemInstance: 3841
  Info: itemInstance: 3861
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3915
  Info: itemInstance: 3841
  Info: itemInstance: 3861
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3915
  Info: itemInstance: 3841
  Info: itemInstance: 3861
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3915
  Info: itemInstance: 3861
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3915
  Info: itemInstance: 3861
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3859
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3915
  Info: itemInstance: 3841
  Info: itemInstance: 3861
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3837
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3837
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3915
  Info: itemInstance: 3841
  Info: itemInstance: 3861
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3915
  Info: itemInstance: 3841
  Info: itemInstance: 3861
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3915
  Info: itemInstance: 3841
  Info: itemInstance: 3861
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3915
  Info: itemInstance: 3841
  Info: itemInstance: 3861
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3915
  Info: itemInstance: 3861
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3837
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3837
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3915
  Info: itemInstance: 3841
  Info: itemInstance: 3861
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3861
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3915
  Info: itemInstance: 3841
  Info: itemInstance: 3861
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3915
  Info: itemInstance: 3841
  Info: itemInstance: 3861
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3543
  Info: itemInstance: 3853
  Info: itemInstance: 4050
  Info: itemInstance: 4053
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3853
  Info: itemInstance: 4046
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3853
  Info: itemInstance: 4046
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3853
  Info: itemInstance: 4046
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3853
  Info: itemInstance: 4046
  Info: DEBUG: ### (0) ### -> B_Scale
  Info: itemInstance: 3853
  Info: itemInstance: 4046
  Info: DEBUG: ### (0) ### -> B_InitGuildAttitudes
  Info: Inserting player of class 'PC_HERO' at startpoint 'zCVobStartpoint:zCVob'
  Info: itemInstance: 4128
  Info: Zen-File found! Size: 2139449
  Info: Reading...
  Info: Reading 7360 blocks
  C:\Users\dat\Desktop\regoth2\REGoth\lib\ZenLib\zenload\zCCSLib.cpp(47):[__cdecl
  ZenLoad::zCCSLib::zCCSLib(const class std::basic_string<char,struct std::char_tr
  aits<char>,class std::allocator<char> > &)] Valuetype name does not match expect
  ed type. Value:subType

**Comment by degenerated1123** [comment]
1.) Right, we don't need all that case-insensitive-path-searching on windows. Will change!

2.) Windows handles paths with / instead of \ perfectly well!

3.) Seems like it is not the ZEN-file itself, but rather the Cutscene-library (aka. OU.bin / OU.dat). Would you mind sending me yours via email or something, so I can take a look at how the format differs?
You can actually circumvent this by just renaming that file in your _work-directory of Gothic. Dialogs won't work, though.

**Comment by ArrrHub** [comment]
A.d. 2 - I could swear I have typed "\\" instead of "\". Weird...
Anyway fopen failed with "/" as it didn't find the file - "\\" works properly.

A.d 3 - How should I rename it? And of course, I'll share the file with you as soon as I can :)

**Comment by degenerated1123** [comment]
2.: What exactly fails to open with / then? Right now I am on windows and can test this.

3.: Just anything, so REGoth can't find it, so it won't crash when loading. You should be able to get into the game like this.

**Comment by ArrrHub** [comment]
2: Try running it from Visual Studio while debuggging. Pretty much every file where you have hardcoded the path. (You can try the OU.bin)

**Comment by degenerated1123** [comment]
There was actually a missing / in front of the OU-path, so when merging it with the game-directory, it got the path wrong, if you didn't supply the game-root with a / or \ at the end.

**Comment by ArrrHub** [comment]
I fixed it as well, but the problem remained until I switched to Windows-default '\\'

**Comment by degenerated1123** [comment]
That is strange, it's working fine for me! I'll push my fixes in a minute. Maybe I did something else which makes it work for me.

**Comment by degenerated1123** [comment]
Okay, I pushed my code. Does it work now? Works fine for me, at least.

**Comment by ArrrHub** [comment]
So it all works except for the main issue

**Comment by degenerated1123** [comment]
Fixed this a while ago. I wasn't reading the chunk-end-tag from dialog-lines of the OU-file, which makes me wonder how it could have worked for me on the german versions.
