### ISSUE TITLE
Current state of the engine

### ISSUE THREAD

**Issue by Soofe** [degenerated1123/REGoth#15]
Hello,

First of all, thank you for your work, it's my favourite game by far.
Would it be possible to roughly add the current state of the engine? Like what works and what doesn't ?

Thanks!

**Comment by degenerated1123** [comment]
I'm doing videos about the current state of the engine on my youtube-channel every now and then. So far I have these three:
https://www.youtube.com/watch?v=8bLAGttYYpY
https://www.youtube.com/watch?v=Z1mlI9qxkzc
https://www.youtube.com/watch?v=R3F4WY6A060

I may also start to release (windows)binaries for everyone to try it out by themselves, soon.

**Comment by degenerated1123** [comment]
Windows-binaries are now automatically built and uploaded as github-release!

**Comment by wisien92** [comment]
Any videos showing off progress coming (loot of commits on git lately :))?

**Comment by degenerated1123** [comment]
I planned on doing one over the next week. Maybe even with commentary, if my English doesn't turn out to be too bad. ;)
But I thought it might be more interesting to watch and I need to practice anyways.

**Comment by degenerated1123** [comment]
Latest video here: https://www.youtube.com/watch?v=heg49o78Ii4

I have also started writing a wiki for REGoth, which will include a list of what works and what not.
