### ISSUE TITLE
Conversion error durring compilation

### ISSUE THREAD

**Issue by Leinnan** [degenerated1123/REGoth#18]
[ 93%] Building CXX object CMakeFiles/engine.dir/src/content/Texture.cpp.o
/media/linux/Gry/REGoth/src/content/Texture.cpp: In member function ‘Handle::TextureHandle Textures::TextureAllocator::loadTextureRGBA8(const std::vector<unsigned char>&, uint16_t, uint16_t, const string&)’:
/media/linux/Gry/REGoth/src/content/Texture.cpp:79:118: error: invalid conversion from ‘unsigned int’ to ‘bgfx::TextureFormat::Enum’ [-fpermissive]
  bgfx::TextureHandle bth = bgfx::createTexture2D(width, height, 1, bgfx::TextureFormat::RGBA8, BGFX_TEXTURE_NONE, mem);
                                                                                                                      ^
In file included from /media/linux/Gry/REGoth/src/handle/HandleDef.h:4:0,
                 from /media/linux/Gry/REGoth/src/content/Texture.h:3,
                 from /media/linux/Gry/REGoth/src/content/Texture.cpp:1:
/media/linux/Gry/REGoth/lib/bgfx-cmake/bgfx/include/bgfx/bgfx.h:1654:16: note:   initializing argument 5 of ‘bgfx::TextureHandle bgfx::createTexture2D(uint16_t, uint16_t, bool, uint16_t, bgfx::TextureFormat::Enum, uint32_t, const bgfx::Memory*)’
  TextureHandle createTexture2D(
                ^~~~~~~~~~~~~~~
/media/linux/Gry/REGoth/src/content/Texture.cpp:79:118: error: invalid conversion from ‘const bgfx::Memory*’ to ‘uint32_t {aka unsigned int}’ [-fpermissive]
  bgfx::TextureHandle bth = bgfx::createTexture2D(width, height, 1, bgfx::TextureFormat::RGBA8, BGFX_TEXTURE_NONE, mem);
                                                                                                                      ^
In file included from /media/linux/Gry/REGoth/src/handle/HandleDef.h:4:0,
                 from /media/linux/Gry/REGoth/src/content/Texture.h:3,
                 from /media/linux/Gry/REGoth/src/content/Texture.cpp:1:
/media/linux/Gry/REGoth/lib/bgfx-cmake/bgfx/include/bgfx/bgfx.h:1654:16: note:   initializing argument 6 of ‘bgfx::TextureHandle bgfx::createTexture2D(uint16_t, uint16_t, bool, uint16_t, bgfx::TextureFormat::Enum, uint32_t, const bgfx::Memory*)’
  TextureHandle createTexture2D(

**Comment by degenerated1123** [comment]
Would you mind trying to reclone everything? bgfx changed the API for textures and I had to deal with that as well.

I actually forked bgfx to stay on a version that works, but somehow messed up the change of repositories in the submodule-config.

Cloning again should work, since travis (automated build server running ubuntu) compiles this without any problems.

**Comment by ousnius** [comment]
I deleted my folder and cloned + cmake'd again, but still get the same issue with MSVC 2017 (seems like the bool hasMips is missing?).

Another issue I have might be related to VC++ 2017, which is that it can't find the external symbol "__iob_func" for the flac.lib in "_FLAC__stream_decoder_reset". Maybe they renamed that one for MSVC?

**Comment by degenerated1123** [comment]
That is really strange. Yes, the hasMips-parameter was removed. However, that was kind of weird anyways, since it just happened all if the sudden.

Does a `git submodule update --recursive` help?

**Comment by degenerated1123** [comment]
So, I did a fresh clone by using only `git clone --recursive <url>` and I was able to build it just fine!

Did you clone without the `--recursive` and updated the submodules later?

**Comment by ousnius** [comment]
Weird. I cloned according to your instructions in Bash, which is:
git clone --recursive https://github.com/degenerated1123/REGoth.git
git pull --recurse-submodules
git submodule update --remote --recursive

**Comment by degenerated1123** [comment]
Okay, I think I get it. Submodules are new to me as well, even though I have used them for a while now. They are really useful on the one hand, but can be pretty messy on the other one.

I don't know why, but updating the submodules using `git submodule update --remote --recursive` fetches newer commits than in my fork? Anyways, I'll quickly fix the code and git config.

**Comment by degenerated1123** [comment]
Allright! That should be it!

For further updates, a `git pull --recurse-submodules` will be sufficient.

**Comment by Soofe** [comment]
Can confirm, compiles and works like a charm on Manjaro.

**Comment by degenerated1123** [comment]
That's good to hear! Thanks for testing!
