### ISSUE TITLE
Failed to start game in world.zen

### ISSUE THREAD

**Issue by Leinnan** [degenerated1123/REGoth#2]
:<
```

Info: ZEN: Reading world...
Info: oCWorld reading chunk: MeshAndBsp
Info: ZEN: Reading mesh...
Info: numPolys: 480135
Info: Num nodes: 6644
Info: Found 105650 non lod polys
Info: Reading mesh '' (Version: 9)
Info: Found 55439 vertices
Info: ZEN: Done reading mesh!
Info: oCWorld reading chunk: VobTree
Info: oCWorld reading chunk: WayNet
Info: Loading 20 freepoints
Info: Loading 3500 edges
Info: MorphProtoName: WATERPLANT_1
/home/piotr/REGoth/src/engine/World.cpp(191):[void World::WorldInstance::initializeScriptEngineForZenWorld(const string&)] Failed to find GOTHIC.DAT!
Info: Initializing scripts for world: world
[1]    16491 segmentation fault (core dumped)  ./REGoth -g "/media/wszystko/Gry/Piranha Bytes/Gothic" -w world.zen

```

Path to Gothic.dat file:
/media/wszystko/Gry/Piranha Bytes/Gothic/_Work/Data/Scripts/_Compiled/Gothic.dat

**Comment by degenerated1123** [comment]
I really need to sort out the case-senstivity of linux systems and Gothic. PB wasn't really consistent on what cases their files are named.
The Gothic.DAT is expected in a path like this:
`/_work/DATA/scripts/_compiled/GOTHIC.DAT`. All cases must be right, otherwise it won't load.

I'll implement a better search for that file.

**Comment by Leinnan** [comment]
https://www.youtube.com/watch?v=cDDEP5r6a38 
Test video.

**Comment by degenerated1123** [comment]
Nice that it runs for you! I should probably implement some mouse controls, as it seems.
Also I forgot to put the better world-shader into the right folder, which displays the "shadows" baked into the worldmeshes vertices.

Thanks for the video, as well!

**Comment by Leinnan** [comment]
Made a better search for that file sounds like a good exercise for someone with basic knowledge about Linux and C++ like me. I will try help with this. :smiley:

**Comment by degenerated1123** [comment]
That would be awesome!

So that would be a function, which gets a path and returns the case-corrected version of it?
There are platform-independent functions for file-handling in Utils.h, which you can use as a base. That would also be a nice place to put such a function.
