### ISSUE TITLE
Compile time error

### ISSUE THREAD

**Issue by Aquaz** [degenerated1123/REGoth#20]
Aren't some of the dependency libraries missing updates (perhaps some changes are not synced with remote repo?).

The compiler complains about remoteItem function being not available

/home/sebbie/apps/clion-2016.3/bin/cmake/bin/cmake --build /home/sebbie/REGoth/cmake-build-debug --target REGoth -- -j 4
[  0%] Linking C static library ../libadpcm.a
[  0%] Linking CXX static library ../../../libsquishd.a
[  0%] Linking CXX static library ../../libutils.a
[  0%] Linking C static library ../libbgfx3rdParty.a
[  1%] Built target adpcm
[  1%] Linking C static library ../../libvdfs.a
[  3%] Built target squish
[  5%] Built target utils
[  5%] Linking CXX static library ../../../libBulletSoftBody.a
[  6%] Built target vdfs
[  6%] Linking CXX static library ../../../libBulletCollision.a
[ 11%] Built target bgfx3rdParty
[ 11%] Linking CXX static library ../../../libBulletDynamics.a
[ 13%] Built target BulletSoftBody
[ 13%] Linking CXX static library ../../../libLinearMath.a
[ 13%] Linking C static library ../../libglfw3.a
[ 16%] Built target LinearMath
[ 17%] Linking CXX static library ../../../../libsfml-system-s-d.a
[ 21%] Built target glfw
[ 21%] Linking C static library ../libbgfx.a
[ 25%] Built target sfml-system
[ 26%] Linking C static library ../../libzenload.a
[ 36%] Built target BulletDynamics
[ 36%] Linking CXX static library ../../../../libsfml-audio-s-d.a
[ 43%] Built target bgfx
[ 44%] Linking C static library ../libbgfx_common.a
[ 49%] Built target sfml-audio
[ 73%] Built target BulletCollision
[ 77%] Built target zenload
[ 77%] Linking C static library ../../libdaedalus.a
[ 83%] Built target bgfx_common
[ 84%] Built target daedalus
Scanning dependencies of target engine
[ 86%] Building CXX object CMakeFiles/engine.dir/src/components/AnimHandler.cpp.o
[ 86%] Building CXX object CMakeFiles/engine.dir/src/components/Vob.cpp.o
[ 86%] Building CXX object CMakeFiles/engine.dir/src/components/VobClasses.cpp.o
[ 86%] Building CXX object CMakeFiles/engine.dir/src/components/EntityActions.cpp.o
/home/sebbie/REGoth/src/components/VobClasses.cpp: In function ‘Handle::EntityHandle VobTypes::initItemFromScript(World::WorldInstance&, size_t)’:
/home/sebbie/REGoth/src/components/VobClasses.cpp:64:44: error: ‘class Daedalus::GameState::DaedalusGameState’ has no member named ‘removeItem’; did you mean ‘createItem’?
     world.getScriptEngine().getGameState().removeItem(h);
                                            ^~~~~~~~~~
[ 86%] Building CXX object CMakeFiles/engine.dir/src/engine/BaseEngine.cpp.o
make[3]: *** [CMakeFiles/engine.dir/build.make:135: CMakeFiles/engine.dir/src/components/VobClasses.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Makefile2:83: CMakeFiles/engine.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1783: src/target/CMakeFiles/REGoth.dir/rule] Error 2
make: *** [Makefile:526: REGoth] Error 2

**Comment by degenerated1123** [comment]
Both Travis and AppVeyor seem to compile everything just fine. They both do a completely fresh clone for every build, so maybe you missed some update of ZenLib, because the function is actually [there](https://github.com/degenerated1123/ZenLib/blob/master/daedalus/DaedalusGameState.h#L118).

What should work, is, `git submodule update`. If that doesn't work, you could try a fresh clone.
Oh the joy of git-submodules.

**Comment by Aquaz** [comment]
Well, that's interesting. Indeed, after cloning the repository again, the build is successful, it seems the recursive pull is not always working... Closing the issue.
