### ISSUE TITLE
Wrong encoding for dialogues in Polish

### ISSUE THREAD

**Issue by Soofe** [degenerated1123/REGoth#22]
Hello,

When initiating a dialog with Xardas, it has the wrong encoding for Polish characters (at least on Linux).

Nothing of value in the terminal output but here's a screenshot :

![screenshot from 2016-12-23 19-34-13](https://cloud.githubusercontent.com/assets/4224655/21460319/22c745a0-c947-11e6-9d19-e87cde025860.png)

I can re-test it anytime if need be.

**Comment by degenerated1123** [comment]
I sadly have no idea on how it is supposed to look like, as I know pretty much nothing about polish. Do you mind making me a reference-picture from the original and describe what exactly is wrong in more detail?

**Comment by rhobariii** [comment]
This is how it is supposed to look in Polish:

Co możemy zrobić?
Zatem wynośmy się stąd czym prędzej?
Potrzebuję broni.

It is an encoding issue.

**Comment by degenerated1123** [comment]
Ah, I see! 

In Gothic each characters byte-value is directly mapped to a part of the font-texture. I really wonder how that could go wrong. Maybe they have multiple font-textures or something else I haven't implemented yet. 

At least the german and english versions seem to use something like latin-1 for encoding. I have no idea if that was changed for polish or russian, but I'll take a look.

**Comment by rhobariii** [comment]
Here's the Polish font texture files: https://www.dropbox.com/s/zwbi56ej8bhcwh0/FontsPolish.zip?dl=1

**Comment by degenerated1123** [comment]
Is encoding on the actual dialogue-lines correct, by any chance?
They come from a different source than the dialogue-options, which could be read or encoded differently...

**Comment by Soofe** [comment]
It doesn't seem to be the case.

For example, in "DIA_Addon_BDT_1064_L.d" I have this line :
`AI_Output (self, other,"DIA_Addon_Dexwache_Add_04_01");  //Chcesz oberwaæ, co? Zrób jeszcze JEDEN krok, a zrzucê ciê z urwiska.`

The comment should be `Chcesz oberwać, co? Zrób jeszcze JEDEN krok, a zrzucę cię z urwiska.`

**Comment by degenerated1123** [comment]
The actual dialogue-lines are read from the OU-file. Is this even right in the original game? I am reading the compiled scripts in binary mode, so there is no encoding happening, as far as I can tell.

**Comment by Soofe** [comment]
Do you mean the Ou.csl file ? If so, it's the wrong encoding when I open it on Linux but it displays correctly in-game.

I'm trying to make some scripts to determine the encoding of the file because when I run `file -bi` on the dialog, it says `charset=unknown-8bit`.

**Comment by degenerated1123** [comment]
They should be latin-1 encoded. Would you mind sending me your GOTHIC.DAT-file, so I can take a look at what goes wrong?

**Comment by Soofe** [comment]
Here you are :

[GOTHIC.zip](https://github.com/degenerated1123/REGoth/files/671542/GOTHIC.zip)

**Comment by Soofe** [comment]
I've actually ran a script to convert from every possible charset to UTF-8 and I've found out that it is CP-1251.

**Comment by degenerated1123** [comment]
Makes sense. Now, there are no characters like "ä" or "ß" as you have in german, for example. I guess they have some code somewhere to do the conversion if the laguage is set to polish or russian. I don't know how the game detects that, though.

**Comment by rhobariii** [comment]
Or it was modified directly by the translators in the engine?

**Comment by Soofe** [comment]
Oh sorry, misread the output, it is CP-1250 actually.

I don't know if the language is set explicitely somewhere but upon installing SystemPack and stuff like that, you have to pick the language manually.

**Comment by degenerated1123** [comment]
It has to be in there somewhere, though, as you can use the 2.6 (fix) version just fine for all languages.
I'll see if I can find something in the sources of the systempack.

**Comment by Soofe** [comment]
If it helps, there is a flag `Polish_version=1` in SystemPack.ini. Maybe other languages are rendered correctly.

**Comment by degenerated1123** [comment]
Can't find anything about that in their source: https://github.com/GothicFixTeam/GothicFix
Since I'm not reading from any textfiles, but all binary, I don't think there should be any differences in byte-values, so no need to transfer to an other encoding... But then, why is it still not working?

I haven't seen anything language related yet while working with the gothic engine either. This is really weird.

**Comment by Czarek22089** [comment]
I just tested windows version (0.1.50) and there is no problem with polish symbols, if that help in some way.

**Comment by Soofe** [comment]
It would be nice if another Polish Linux user could confirm this.

**Comment by czapnaper** [comment]
On the Linux version 0.1.50 here is no problem with polish symbols . https://www.dropbox.com/s/2jh2bqml83ovv01/gothic.png?dl=0

**Comment by degenerated1123** [comment]
Now that is weird. I'm reading the characters as straight bytes and doing a direct mapping to the font texture.

**Comment by Soofe** [comment]
It may be a problem on my end then, don't bother with it for now. I'll try a few things to see how it goes maybe.

**Comment by fmj02** [comment]
Fonts are textures with corresponding .fnt files. I'm sure there are different font textures for Russian client and the same font textures for normal alphabet (English, German, Polish etc.) but I can be wrong. Anyway on my polish version of Gothic on windows it displays correctly :)

![xx](https://cloud.githubusercontent.com/assets/3116731/21472760/980af22e-cae8-11e6-9858-6e96aa0fce4f.png)
![fonts](https://cloud.githubusercontent.com/assets/3116731/21472761/a0b4114e-cae8-11e6-99f5-1e6368f0aa3f.png)

**Comment by inobelar** [comment]
Russian font textures works well (ubuntu 15.10 x64) :smiley: 

![image](https://cloud.githubusercontent.com/assets/20372668/21480673/fd299730-cb67-11e6-93df-f3b873265c90.png)

**Comment by Soofe** [comment]
Can anybody provide me a Polish Ou.bin file ?
Found in `_work/Data/Scripts/CONTENT/CUTSCENE`.

You can drag&drop it on Github after zipping it.

Thanks!

**Comment by fmj02** [comment]
@Soofe 
https://mega.nz/#!y11RnQbR!NN9geBouYPyK5K_-AhEvpxxukKaDc5ON6-43zakuN0I

**Comment by Soofe** [comment]
@fmj02 Didn't work, thanks anyway!

Ok, here's what I did. I had an installer with the Polish translation that didn't work on wine (since only cdp.pl has the rights to distribute the Polish version, you can't have it on GOG) so I manage to get access to a Windows PC and I've reinstalled everything, applied the translation, then I've copied the whole folder back to my Linux machine. It works perfectly now, the console output is still wrong but that doesn't matter.

It was thus a problem on my end. You can mark this issue as solved. 
Thanks everybody!

**Comment by degenerated1123** [comment]
Wow, didn't expect that many posts over christmas! Anyways, glad this issue is something I do not need to fix, since getting encodings right is always a hassle.

My guess of what when wrong is, that you may saved your daedalus-files using the wrong encoding at some point, which the script-compiler then picked up.

Console-Output is always wrong on non ASCII-Characters, as I didn't bother with the encoding there, by the way.
