### ISSUE TITLE
No clear dependecies listed for major distros

### ISSUE THREAD

**Issue by aleferri** [degenerated1123/REGoth#23]
What are you using?

gcc 6.2.1, gcc-c++ 6.2.1, cmake 3.6.1, fedora 25, git 2.9.3.

What happened?

CMake complain it cannot find OpenGL, OpenMP & Vulkan, then fire an error from CMakeList.txt [249] in /lib/glfw "RandR library not found".

There are other packages i have to install before running CMake?

**Comment by degenerated1123** [comment]
You can check out the travis.yml found in the repository-root, which contains a list of all packages I had to install for building on Ubuntu 12. I think you are missing dev-versions of some packages.

**Comment by aleferri** [comment]
Solved for me, i needed some other packages other than listed. Please accept my PR.

**Comment by aleferri** [comment]
Ok, now the wiki has a page for this.
