### ISSUE TITLE
Missing shaders?

### ISSUE THREAD

**Issue by Aquaz** [degenerated1123/REGoth#26]
Aren't some shaders missing in the recent build? This is what happens when I'm trying to run the engine with Gothic 1 : 

Info: Initializing item: MENU_ITEM_TALENT_13_TITLE
Info: Initializing item: MENU_ITEM_TALENT_13_SKILL
Info: Loading texture: BAR_BACK.TGA
Info: Loading texture: BAR_HEALTH.TGA
Info: Loading texture: BAR_MANA.TGA
/home/sebbie/REGoth/lib/bgfx-cmake/bgfx/src/bgfx_p.h (3445): BGFX Creating uniform (handle   2) u_FogColor
/home/sebbie/REGoth/lib/bgfx-cmake/bgfx/src/bgfx_p.h (3445): BGFX Creating uniform (handle   3) u_FogNearFar
/home/sebbie/REGoth/src/utils/Utils.cpp(185):[const bgfx::Memory* Utils::loadMem(bx::FileReaderI*, const char*)] Failed to load shader at: shaders/glsl/vs_world_instanced.bin
/home/sebbie/REGoth/lib/bgfx-cmake/bgfx/src/bgfx.cpp (2854): BGFX CHECK _mem can't be NULL
Trace/breakpoint trap (core dumped)

**Comment by degenerated1123** [comment]
Oh right! I totally forgot about that. In the meantime, just copy any other shader and name it like the missing one. It is not used anywhere.

**Comment by Aquaz** [comment]
Already did that but something didn't seem right :D : 

![screenshot_2016-12-30_23-25-39](https://cloud.githubusercontent.com/assets/22575702/21573660/63e34818-cee7-11e6-9990-76926f0b883a.png)

So I thought it had something to do with the missing shaders :-)

**Comment by degenerated1123** [comment]
Ah no, that is just an other thing I forgot. I got so used to it that I didn't bother anymore! :D

In fact, I have a lot of commits waiting to be pushed and I just don't want to bother with git currently. I'll upload everything on the next couple of hours or so.

**Comment by degenerated1123** [comment]
Wait a second. The leg is missing on my system, but not that long! That looks hilarious! :D

**Comment by Aquaz** [comment]
Haha, alright, no worries ;).

Aye, I couldn't stop laughing for a while :smile:

**Comment by degenerated1123** [comment]
Should be fixed now!
