### ISSUE TITLE
Dialogs do not work anymore

### ISSUE THREAD

**Issue by Kaffeine** [degenerated1123/REGoth#32]
Hello and thanks for the project.

Since commit 5f42f82433516de62aa6704d55824f042eb6e699, dialogs have no input.

```diff
void UI::Hud::onInputAction(UI::EInputAction action)
{
-    if(!m_pDialogBox->isHidden())
-        m_pDialogBox->onInputAction(action);
}
```

It seems that we (reasonably) don't want to check all menus via hand-written code, but now we have no obvious way to propagate input to dialogs and no way to close Menu_Status on sequential GLFW_KEY_B pressed (ATM we open more and more status menus on each B pressed event).

I would like to fix it, but I have no idea how.

**Comment by degenerated1123** [comment]
I think I already fixed that isse, but haven't pushed the code yet. There is still some more stuff I need to do and I'm pretty stressed out from university right now. Fix will come soon, though!

**Comment by Kaffeine** [comment]
If you'll create some list of "junior job" or add some issues it would be very appreciated.
I'm a C++ programmer and I love the game, but I don't know where to start.

**Comment by astillich** [comment]
I'd like to help as well. I started fiddling around with the script externals, maybe implement some low hanging fruits but I don't know if it even makes sense at this point. I discovered about 80 functions which are not stubbed but listed in the Gothic modding documentation. I'd write a script which generates these stubs and contribute them, if this makes any sense?

**Comment by degenerated1123** [comment]
@Kaffeine: I really should put up a list of simple stuff, nice idea.
@astillich: There are a lot of externals still missing, and yes, my script didn't seem to have caught all of them. A more complete list would help a lot.

Also, off the top of my head, there is one quest in the swamp-camp, which can't be completed yet because there is a simple function missing to search for monsters in range. If you want, you could look into that :)

The quest is the one where you have to kill all the bloodflys in the swamp around some of the novices. Just take a look at the script files for that, you'll see what I mean.

**Comment by astillich** [comment]
Ok I'll have a look sometime during this week. [Here](http://pastebin.com/Hf1t1zwA) is the list I've extracted from the [Gothic1](http://www.worldofgothic.de/modifikation/index.php?go=g2functions) / [Gothic2](http://www.worldofgothic.de/modifikation/index.php?go=g1functions) function lists. I just realized that some of them aren't actually missing (like Wld_GetDay). My script cross referenced the function lists with the code in **logic/scriptExternals** but some of the functions are implemented elsewhere. I'll sort them out and add stubs.

**Comment by astillich** [comment]
@degenerated1123 Do you mean the quest [The Swampweed Harvest] (http://mikesrpgcenter.com/gothic/sidequests.html) and the two functions in this script:

`       
 if ( Wld_DetectNpc(self,bloodfly,ZS_MM_Rtn_Wusel,-1) && (Npc_GetDistToNpc(self, other)<2000) ) //other = nearest Bloodfly (Instance/ZS/Guild)
        //wenn keine Bloodfly in 40m, dann other noch unver<E4>ndert (= hero)
        {
` 
Or do you mean another quest? 

They are both implemented but exist as both stub and actual implementation. Maybe the stub overrides the  implementations? Registration order and the fact that DaedalusVM::registerExternalFunction() blindly overwrites the previously registered function suggests the opposite, though.

**Comment by degenerated1123** [comment]
It could probably be that these functions just don't check if the found npc is dead or not. So even-better, just throw in a check for that in (there is PlayerController::getBodyState() which is BS_DEAD then) and the quest should be possible to complete!

**Comment by astillich** [comment]
Yes you [did](https://github.com/degenerated1123/REGoth/blob/master/src/logic/scriptExternals/Externals.cpp#L684). :D 

Okay, I'll add the check and remove the obsolete stubs.

**Comment by degenerated1123** [comment]
Interesting. I think I even remember writing that :D

**Comment by degenerated1123** [comment]
Fixed.
