### ISSUE TITLE
OpenMP (Mac)

### ISSUE THREAD

**Issue by gbudny** [degenerated1123/REGoth#7]
Hi

I tried to compile this game on a Mac, but I noticed the issue with the OpenMP. 

Why do I need to install a compiler with the OpenMP on the Mac?

cmake -DCMAKE_BUILD_TYPE=Release ..
-- Try OpenMP C flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-fopenmp=libomp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp=libomp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
CMake Error at /usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find OpenMP (missing: OpenMP_C_FLAGS OpenMP_CXX_FLAGS)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/FindOpenMP.cmake:234 (find_package_handle_standard_args)
  CMakeLists.txt:35 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/Users/gbudny/Desktop/downloads/REGoth-master/build/CMakeFiles/CMakeOutput.log".
See also "/Users/gbudny/Desktop/downloads/REGoth-master/build/CMakeFiles/CMakeError.log".

**Comment by degenerated1123** [comment]
What compiler are you using then? I have no experience with macs whatsoever, sorry.

You'll need a pretty up-to-date compiler anyways, which supports C++11. I doubt that the compiler is going to handle that if OpenMP isn't even supported, but I could very well be wrong about that one.

Anyways, you can just remove the OpenMP-stuff from the CMakeLists.txt and try again. Maybe it works?

**Comment by degenerated1123** [comment]
Seems like Apple really disabled OpenMP. As I said, just remove the flags and if the compiler is new enough it should work.

You are the first to compile it on a mac, though.

**Comment by gbudny** [comment]
I found the solution, and it works:

"OpenMP and MPI are two entirely different things.

OMP requires compiler support, which on OS X you'll need via Homebrew. (you can also install MPI via Homebrew too, which is nice).

brew install clang-omp
After you've installed clang-omp, you can then tell CMake to use that compiler by invoking it like so.

CC=clang-omp CXX=clang-omp++ cmake <insert your normal cmake parameters here>"

http://stackoverflow.com/questions/34216589/cmake-does-not-work-with-openmp-on-maverick

**Comment by abelsromero** [comment]
This fix does not seem to work now. Many places end up pointing, but I haven't been able to make it work: https://stackoverflow.com/questions/38971394/brew-install-clang-omp-not-working

any help?
